## 输出调试
`cerr << `一般搭配文件输出（正常输出到文件，异常输出到屏幕）
宏`__func__`，`__FILE__`, `__LINE__`, `__DATE__`, `__TIME__`可以帮你输出一些常用信息（注意大小写）
如func是代码所在行属于哪个函数，file是当前文件，line是代码所在行（避免修改代码是行位置改变又要去改调试代码）

## assert
`#define NDEBUG`禁止assert
assert是断言括号里的内容成立

## 异常处理
### try throw catch
```c++
void B() {
	throw 1;
	cout << "B" << endl; //throw后，不执行
}

void A() {
	B();
	cout << "A" << endl;//接收到throw但没有catch，不执行
}

int main() {
	try {
		A();
	}
	catch(int &err) {//接到int类型的值存为err
		cerr << err << endl;
	}
	catch(...) {//可以连着写好多个catch， 优先执行上面的
	}
	return 0;
}
```
throw于返回值不同，即使是临时变量，也可用引用形式去catch。并推荐用引用去catch
由于catch后不会再往上级返回，如果有这种需求，可以在catch里再throw一次

函数声明时再括号后大括号前可以声明
`throw()`表示函数很安全，不会有任何异常（如果抛出了异常，程序终止，为的是避免不该异常的函数出错，如析构函数）
`throw(int, double)`表示函数可以抛出int和double类型
不加表示可以抛出任何类型

`catch(...)`可接受任何类型

### exception类
`include <stdexcept>`
[继承结构](https://blog.csdn.net/qq_37968132/article/details/82431775)
`catch (exception &err) { cerr << err.what() << endl; }`

### noexcept
c++11里对函数声明时的throw()给到`dynamic exception specifications are deprecated`
这是因为throw不常用（throw(int,double)这样很多余？）
而是将原来放throw()的地方改为放noexcept
`noexcept`声明的效果同之前的`throw()`

`noexcept()`括号里可以加条件
如`noexcept(noexcept(x.swap(y)))`表示当里面那个不丢异常时，我就不丢异常
不写括号时，默认括号里是true
如 vector里自定义的move不写noexcept编译器不敢用

## clock
`clock_t`实际为long
`clock_t st, ed;`, `st=clock(); ... ed = clock();`, `ed - st`可用于测试程序中部分代码的运行时间
`CLOCKS_PER_SEC`表示一秒对应clock里多少个计时单位，我这是1000000

linux命令`time ./a`可以测整个程序时间